---
abstract: 'An evil mod_perl-like Mason handler under L<Plack>'
author:
  - 'Ævar Arnfjörð Bjarmason <avar@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300040, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-MasonX-ApacheLikePlackHandler
no_index:
  directory:
    - t
requires:
  HTML::Mason: 1.50
  Test::More: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=HTML-MasonX-ApacheLikePlackHandler
  homepage: http://metacpan.org/release/HTML-MasonX-ApacheLikePlackHandler
  license: http://dev.perl.org/licenses/
  repository: git://github.com/avar/html-masonx-apachelikeplackhandler.git
version: 0.01
